let map_menu;
let worldMapConteiner;
let worldmapContent;
let mapCenter = {toX: 0, isX: 0, toY: 0, isY: 0,};
let way_comming = null;
let tableButton;
let actualPosition = {x:0, y:0};
let activeWindow = -1;
let speed = 10;
let actualMap;
let poktable;
let activeButton = null;
let worldMapTable;
let worldMapWindow;
let dex_containter;
let dex_dataPlace;
let dex_baseStats;
let dex_pokemonList;

let admin_conteiner;
let admin_list;
let admin_content;
let adm_selectedMapItem = 0;
let adm_mapTable;
let noErrors;